In [13]:
import numpy as np

In [1]:
import torch

In [7]:
SEED = 123
torch.manual_seed(SEED)

In [10]:
x = torch.randn(2, 3)

In [11]:
print(x)
print(x.type)
print(x.shape)

tensor([[-0.9724, -0.7550,  0.3239],
        [-0.1085,  0.2103, -0.3908]])
<built-in method type of Tensor object at 0x0000026E72A38230>
torch.Size([2, 3])


In [17]:
t = torch.Tensor([[3, 2], [1, 5]])

In [18]:
print(t)

tensor([[3., 2.],
        [1., 5.]])


In [19]:
u = torch.Tensor([[4, 3, 5], [1, 2, 1]])

In [21]:
torch.mm(t, u)

tensor([[14., 13., 17.],
        [ 9., 13., 10.]])

In [23]:
np.dot(t, u)

C:\Users\aswinrajr\AppData\Local\Temp\ipykernel_45128\3867629848.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  np.dot(t, u)


array([[14., 13., 17.],
       [ 9., 13., 10.]], dtype=float32)

In [27]:
print(x)
print(x[[0, 1], [0, 2]])

tensor([[-0.9724, -0.7550,  0.3239],
        [-0.1085,  0.2103, -0.3908]])
tensor([-0.9724, -0.3908])


In [28]:
torch.cat([x, x], dim=1)

tensor([[-0.9724, -0.7550,  0.3239, -0.9724, -0.7550,  0.3239],
        [-0.1085,  0.2103, -0.3908, -0.1085,  0.2103, -0.3908]])

In [29]:
torch.cuda.is_available()

True

In [31]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x = torch.rand(2, 3).to(device)
x.is_cuda

True