In [1]:
import numpy as np

In [2]:
np1 = np.array([1, 2, 3, 4])
np2 = np.arange(5, 15, 4)
np3 = np.zeros(4)
np4 = np.full((5), 6)

list1 = [1, 2, 3, 4]
np5 = np.array(list1)

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

sliced = arr[1:3, 2]

2
(3, 3)
9
int64


In [16]:
print(sliced)
print(sliced.size)
print(sliced.shape)
print(sliced.ndim)

new_sliced = arr[[2,0,1],[2,0,1]]

[6 9]
2
(2,)
1


In [17]:
print(arr)
print(new_sliced)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[9 1 5]


In [18]:
print(arr)
print(arr > 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [19]:
print(arr[arr>2])

[3 4 5 6 7 8 9]


In [22]:
x = np.array([[3, 2, 5], [1, 1, 2], [2, 3, 1]])
y = np.array([[1, 2, 5], [3, 5, 3], [2, 1, 4]])


In [26]:
print(x)
print(y)
print(x+y)
print(np.add(x, y))
print(x-y)
print(np.subtract(x, y))

[[3 2 5]
 [1 1 2]
 [2 3 1]]
[[1 2 5]
 [3 5 3]
 [2 1 4]]
[[ 4  4 10]
 [ 4  6  5]
 [ 4  4  5]]
[[ 4  4 10]
 [ 4  6  5]
 [ 4  4  5]]
[[ 2  0  0]
 [-2 -4 -1]
 [ 0  2 -3]]
[[ 2  0  0]
 [-2 -4 -1]
 [ 0  2 -3]]


In [39]:
print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
print(x.sum(axis=0))
print(x.min(axis=0))
print(x.max(axis=1))

[[3 2 5]
 [1 1 2]
 [2 3 1]]
20
[6 6 8]
[10  4  6]
[6 6 8]
[1 1 1]
[5 2 3]


In [ ]:
print(x)
print(np.array(2)+x)

[[3 2 5]
 [1 1 2]
 [2 3 1]]
[[5 4 7]
 [3 3 4]
 [4 5 3]]


In [53]:
a = np.array([[1, 2, 4]])
b = np.array([3, 4, 5])
c = a.T

In [65]:
print(a.shape)
print(b.shape)
print(c.shape)
d = np.expand_dims(b, 1)
print(a+b)
print(d)
print(d.shape)
print(b+d)

(1, 3)
(3,)
(3, 1)
[[4 6 9]]
[[3]
 [4]
 [5]]
(3, 1)
[[ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]]


In [67]:
d = d.reshape((3))
print(b+d)

[ 6  8 10]


In [73]:
print(x)
print(x.T)
print(np.transpose(x, axes=(0, 1)))

[[3 2 5]
 [1 1 2]
 [2 3 1]]
[[3 1 2]
 [2 1 3]
 [5 2 1]]
[[3 2 5]
 [1 1 2]
 [2 3 1]]


In [74]:
y = np.array([3, 4, 5, 6, 7, 8])

In [82]:
print(y)
print(y.reshape((2, -1)))
print(y.reshape((2, 3, 1)))

[3 4 5 6 7 8]
[[3 4 5]
 [6 7 8]]
[[[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]


In [114]:
y = np.array([[[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3]],
            [[10, 10, 10, 10], [20, 20, 20, 20], [30, 30, 30, 30]]])
print ("y:\n", y)
print ("y.shape: ", y.shape)

y:
 [[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]
y.shape:  (2, 3, 4)


In [119]:
print(y)
np.transpose(y, (2, 1, 0))

[[[ 1  1  1  1]
  [ 2  2  2  2]
  [ 3  3  3  3]]

 [[10 10 10 10]
  [20 20 20 20]
  [30 30 30 30]]]


array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 1, 10],
        [ 2, 20],
        [ 3, 30]]])

In [130]:
z = np.concatenate((y[0, :, :], y[1, :, :]), axis=1)
print(z)

[[ 1  1  1  1 10 10 10 10]
 [ 2  2  2  2 20 20 20 20]
 [ 3  3  3  3 30 30 30 30]]


In [127]:
y.transpose((1, 0, 2)).reshape(3, 8)

array([[ 1,  1,  1,  1, 10, 10, 10, 10],
       [ 2,  2,  2,  2, 20, 20, 20, 20],
       [ 3,  3,  3,  3, 30, 30, 30, 30]])

In [136]:
print(x)
np.stack((x, x), axis=2)

[[3 2 5]
 [1 1 2]
 [2 3 1]]


array([[[3, 3],
        [2, 2],
        [5, 5]],

       [[1, 1],
        [1, 1],
        [2, 2]],

       [[2, 2],
        [3, 3],
        [1, 1]]])

In [152]:
print(x)
k = np.expand_dims(x, 2)
print(k)
print(np.squeeze(k, 2))

[[3 2 5]
 [1 1 2]
 [2 3 1]]
[[[3]
  [2]
  [5]]

 [[1]
  [1]
  [2]]

 [[2]
  [3]
  [1]]]
[[3 2 5]
 [1 1 2]
 [2 3 1]]
